# fly.toml app configuration file generated for hotels-data-merge-fragrant-butterfly-8025 on 2024-10-20T01:53:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hotels-data-merge-fragrant-butterfly-8025'
primary_region = 'syd'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
